<?php

namespace EtoxMicrome\OrigenBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrigenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrigenRepository extends EntityRepository
{
}
