<?php

namespace EtoxMicrome\RelacionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TipoRelacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoRelacionRepository extends EntityRepository
{
}
