<?php

namespace EtoxMicrome\OrigenBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrigenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrigenRepository extends EntityRepository
{

    public function getEvidenciasParaOrigenURL($url)
    {
        $em = $this->getEntityManager();
        $connection=$em->getConnection();
        $user = $connection->getUsername();
        $password = $connection->getPassword();
        $host = $connection->getHost();
        $database=$connection->getDatabase();
        $conn = mysql_connect ($host, $user, $password);
        mysql_select_db($database, $conn);
        mysql_query("SET NAMES 'utf8'");
        $selectSQL="SELECT e.id from Evidencia as e INNER JOIN Origen o ON e.id = o.id where o.url='$url'";
        $result= mysql_query($selectSQL);
        $arrayEvidencias=array();
        while ($row = mysql_fetch_row($result)){
        	#$idEnzyme=$row[0];
        	$evidencia_id=(int)$row[0];
        	$arrayEvidencias[]=$evidencia_id;
        }

        return($arrayEvidencias);
    }

}
