<?php

namespace EtoxMicrome\EvidenciaBundle\Entity;

use Doctrine\ORM\EntityRepository;
#use EtoxMicrome\EvidenciaEntidadBundle\Entity\EvidenciaEntidad;
#use EtoxMicrome\EntidadBundle\Entity\Entidad;

/**
 * EvidenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvidenciaRepository extends EntityRepository
{

}
