<?php

namespace EtoxMicrome\EntidadBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CompuestoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompuestoRepository extends EntityRepository
{
}
