<?php

namespace EtoxMicrome\EntidadBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrganismoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganismoRepository extends EntityRepository
{
    public function getOrganismIdFromName($name){
        $em = $this->getEntityManager();
        $connection = $em->getConnection();
        $user = $connection->getUsername();
        $password = $connection->getPassword();
        $host = $connection->getHost();
        $database=$connection->getDatabase();
        $conn = mysql_connect ($host, $user, $password);

        mysql_select_db($database, $conn);
        mysql_query("SET NAMES 'utf8'");

        $selectSQL="SELECT o.idNCBI FROM Organismo as o, EvidenciaEntidad ee where  o.evidenciaEntidad_id=ee.id and ee.textminingName='$name' limit 1";
        $result= mysql_query($selectSQL);
        $row = mysql_fetch_row($result);
        $idOrganismo=(int)$row[0];
        return($idOrganismo);
    }
}
