<?php

namespace EtoxMicrome\DominioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DominioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DominioRepository extends EntityRepository
{
}
