<?php

namespace EtoxMicrome\EvidenciaDominioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EvidenciaDominioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvidenciaDominioRepository extends EntityRepository
{
}
